'use client';
import { useState } from 'react';
import { products, deliveryFee, formatMoney } from '../lib/siteProducts';
export default function CheckoutClient({ initialProductId }){
 const [productId,setProductId]=useState(initialProductId||products[0].id); const [quantity,setQuantity]=useState(1);
 const [form,setForm]=useState({name:'',phone:'',address:'',number:'',neighborhood:'',complement:'',note:''}); const [loading,setLoading]=useState(false); const [payment,setPayment]=useState(null); const [error,setError]=useState('');
 const product=products.find(p=>p.id===productId)||products[0]; const subtotal=product.price*Number(quantity||1); const total=subtotal+deliveryFee;
 async function submit(e){ e.preventDefault(); setLoading(true); setError(''); setPayment(null); const res=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId,quantity:Number(quantity||1),customer:form})}); const data=await res.json(); setLoading(false); if(!res.ok){setError(data.error||'Erro ao gerar pagamento.'); return;} setPayment(data); }
 return <section className="checkoutGrid"><form className="checkoutForm" onSubmit={submit}><h2>Finalizar pedido</h2><p className="muted">Nome, telefone e endereço são obrigatórios para entrega.</p><label>Produto<select value={productId} onChange={e=>setProductId(e.target.value)}>{products.map(p=><option key={p.id} value={p.id}>{p.name} — {p.size} — {formatMoney(p.price)}</option>)}</select></label><label>Quantidade<input min="1" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label>Nome completo<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Telefone / WhatsApp<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></label><label>Endereço<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} required/></label><div className="twoCols"><label>Número<input value={form.number} onChange={e=>setForm({...form,number:e.target.value})} required/></label><label>Bairro<input value={form.neighborhood} onChange={e=>setForm({...form,neighborhood:e.target.value})} required/></label></div><label>Complemento<input value={form.complement} onChange={e=>setForm({...form,complement:e.target.value})}/></label><label>Observação<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><div className="privacyBox">Seus dados serão usados apenas para processar o pedido e realizar a entrega.</div>{error&&<div className="alert error">{error}</div>}<button className="primaryBtn" disabled={loading}>{loading?'Gerando Pix...':'Gerar Pix automático'}</button></form><aside className="checkoutSummary"><h2>Resumo</h2><h3>{product.name}</h3><p>{product.size}</p><div className="summaryLine"><span>Produto</span><b>{formatMoney(product.price)}</b></div><div className="summaryLine"><span>Quantidade</span><b>{quantity||1}</b></div><div className="summaryLine"><span>Subtotal</span><b>{formatMoney(subtotal)}</b></div><div className="summaryLine"><span>Entrega</span><b>{formatMoney(deliveryFee)}</b></div><div className="summaryLine total"><span>Total</span><b>{formatMoney(total)}</b></div>{payment&&<div className="pixBox"><h3>Pix gerado</h3><p>Escaneie o QR Code ou copie o código Pix.</p>{payment.qrCodeBase64&&<img src={`data:image/png;base64,${payment.qrCodeBase64}`} alt="QR Code Pix"/>}<textarea readOnly value={payment.qrCode||''}/><a className="siteBtn" href={`/pedido?id=${payment.orderId}`}>Ver pedido</a></div>}</aside></section>
}
